name: Build & Deploy (EC2)

#which branch to trigger the workflow on
on:
  push:
    branches: [main]

#to prevent multiple deployments at the same time, we can use concurrency
concurrency:
  group: deploy-prod
  cancel-in-progress: true

#to define constants once and use them across multiple steps/jobs
env:
  BACKEND_IMAGE: codewithaayush7/chat-backend
  FRONTEND_IMAGE: codewithaayush7/chat-frontend

jobs:
  # -----------------------------

  # 1️⃣ BUILD + PUSH IMAGES

  # -----------------------------

  build:
    runs-on: ubuntu-latest #runs a fresh VM for each run

    steps:
      - uses: actions/checkout@v4 #downloads my code to the VM

      - uses: docker/login-action@v3 #logs into Docker Hub(authenticates) so that we can push images
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5 #Take backend folder → run Dockerfile → create image → tag it → push it.
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
            ${{ env.BACKEND_IMAGE }}:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5 #Take frontend folder → run Dockerfile → create image → tag it → push it.
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
            ${{ env.FRONTEND_IMAGE }}:latest

  # -----------------------------

  # 2️⃣ DEPLOY ON EC2

  # -----------------------------

  deploy:
    needs: build #Do not deploy unless build succeeds.
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3 #Connect to my server and run commands there.
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/chatty_with_docker

            export TAG=${{ github.sha }}

            docker compose pull || exit 1
            docker compose up -d --remove-orphans

            sleep 10
            docker compose ps
